[package]
name = "usdpl-rs"
version = "0.1.0"
authors = ["NGnius (Graham) <ngniusness@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "usdpl-core",
    "usdpl-front",
    "usdpl-back"
]
