[package]
name = "usdpl-back"
version = "0.3.0"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/NGnius/usdpl-rs"
readme = "README.md"
description = "Universal Steam Deck Plugin Library back-end"

[features]
default = []
decky = []
crankshaft = []

[dependencies]
usdpl-core = { version = "0.3.0", path = "../usdpl-core" }

# HTTP web framework
warp = { version = "0.3" }
bytes = { version = "1.1" }
tokio = { version = "1.19", features = ["rt", "rt-multi-thread"] }
lazy_static = { version = "1.4" }
