[package]
name = "usdpl-back"
version = "0.2.1"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/NGnius/usdpl-rs"
readme = "README.md"
description = "Universal Steam Deck Plugin Library back-end"

[features]
default = []
decky = []
crankshaft = []

[dependencies]
usdpl-core = { version = "0.1.0", path = "../usdpl-core" }
tungstenite = { version = "0.17" }
